// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Request(arg1) {
  return window['go']['IPC']['Service']['Request'](arg1);
}
