// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {IPC} from '../models';

export function Request(arg1:IPC.Request):Promise<IPC.response>;
